Bootstrap a NestJs GraphQL Starter with SurrealDB and refactor some filenames and fix summary files
surrealdb/tutorials pull request #11
Opened 2022-10-15 22:09 UTC by koakh

added a new tutorial and fix some summary issues, convert filenames to kebab to be consistent

2022-10-16 08:30 UTC, kearfy requested changes

2022-10-16 08:30 UTC, kearfy commented on SUMMARY.md
> +    - [Bootstrap a NestJs GraphQL Starter with SurrealDB](community/05_bootstrap-a-nest-js-graph-ql-starter-with-surreal-db.md)
Looks good, though could you name your own guide also the naming convention? (05_   ->   05-)

2022-10-16 14:56 UTC, koakh commented on SUMMARY.md
> +    - [Bootstrap a NestJs GraphQL Starter with SurrealDB](community/05_bootstrap-a-nest-js-graph-ql-starter-with-surreal-db.md)
nice catch @kearfy, on top of it right now

2022-10-29 19:16 UTC, koakh commented
just close

2022-10-29 19:16 UTC, closed without merging